language: java
jdk:
  - openjdk11

# 어느 브랜치에 push될 때 수행할 것인지?
branches:
  only:
    - main # main branch에 push 될 때만 CI를 수행해라

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# main branch에 push 되었을 때 수행할 명령어
script: "./gradlew clean build"

# CI 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - 'eheh12321@gmail.com'